services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-api

  backend-api:
    build: ./backend
    command: node express.js
    ports:
      - "5001:5001"
    env_file: ./backend/.env
    depends_on:
      - db
      - redis

  backend-worker:
    build: ./backend
    command: node index.js
    env_file: ./backend/.env
    depends_on:
      - db
      - redis

  db:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geoalert
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
