CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  pwd_hash TEXT NOT NULL
);

CREATE TABLE zones (
  id SERIAL PRIMARY KEY,
  geometry GEOMETRY(POLYGON, 4326) NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  event_types TEXT[] NOT NULL
);

CREATE TABLE events (
  id SERIAL PRIMARY KEY,
  event_type TEXT NOT NULL,
  geometry GEOMETRY(POINT, 4326) NOT NULL
);

CREATE TABLE alerts (
  id SERIAL PRIMARY KEY,
  zone_id INTEGER REFERENCES zones(id) ON DELETE CASCADE,
  event_id INTEGER REFERENCES events(id) ON DELETE CASCADE,
  triggered_at TIMESTAMP DEFAULT NOW()
);
